spring.application.name=sistematransportes
server.port=8080

# H2
spring.datasource.url=jdbc:h2:mem:guiasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# AWS S3
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.sessionToken=${AWS_SESSION_TOKEN}
aws.region=${AWS_REGION}
aws.s3.bucket=guias-despacho-bucket

efs.path=/mnt/efs/guias
